require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "tmp/**/*"
    - "db/**/*"
    - "vendor/bundle/**/*"
  SuggestExtensions: false