default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: honda_sorted_number_development
test:
  <<: *default
  database: honda_sorted_number_test
production:
  <<: *default
  database: honda_sorted_number_production
  username: honda_sorted_number
  password: <%= ENV["HONDA_SORTED_NUMBER_DATABASE_PASSWORD"] %>
